version: "3"

services:

  shopware:
    image: dockware/essentials:latest
    container_name: shopware
    ports:
      - "192.168.178.144:80:80"
      - "192.168.178.144:3306:3306"
      - "22:22"
      - "192.168.178.144:8888:8888"
      - "192.168.178.144:9999:9999"
      - "192.168.178.144:9998:9998"
    networks:
      - web
    volumes:
      - "db_volume:/var/lib/mysql"
      - "shop_volume:/var/www/html"

volumes:
  db_volume:
    driver: local
  shop_volume:
    driver: local

networks:
  web:
    external: false