<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBBWyLo0\Shopware_Production_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBBWyLo0/Shopware_Production_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerBBWyLo0.legacy');

    return;
}

if (!\class_exists(Shopware_Production_KernelProdContainer::class, false)) {
    \class_alias(\ContainerBBWyLo0\Shopware_Production_KernelProdContainer::class, Shopware_Production_KernelProdContainer::class, false);
}

return new \ContainerBBWyLo0\Shopware_Production_KernelProdContainer([
    'container.build_hash' => 'BBWyLo0',
    'container.build_id' => '69c5bacc',
    'container.build_time' => 1655819753,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBBWyLo0');
