<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFMCs41g\Shopware_Production_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFMCs41g/Shopware_Production_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerFMCs41g.legacy');

    return;
}

if (!\class_exists(Shopware_Production_KernelProdContainer::class, false)) {
    \class_alias(\ContainerFMCs41g\Shopware_Production_KernelProdContainer::class, Shopware_Production_KernelProdContainer::class, false);
}

return new \ContainerFMCs41g\Shopware_Production_KernelProdContainer([
    'container.build_hash' => 'FMCs41g',
    'container.build_id' => '3493bc34',
    'container.build_time' => 1655819786,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFMCs41g');
