<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHdAyH3E\Shopware_Production_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHdAyH3E/Shopware_Production_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerHdAyH3E.legacy');

    return;
}

if (!\class_exists(Shopware_Production_KernelProdContainer::class, false)) {
    \class_alias(\ContainerHdAyH3E\Shopware_Production_KernelProdContainer::class, Shopware_Production_KernelProdContainer::class, false);
}

return new \ContainerHdAyH3E\Shopware_Production_KernelProdContainer([
    'container.build_hash' => 'HdAyH3E',
    'container.build_id' => 'c50ebccb',
    'container.build_time' => 1655886825,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHdAyH3E');
