<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN3xx8ET\Shopware_Production_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN3xx8ET/Shopware_Production_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerN3xx8ET.legacy');

    return;
}

if (!\class_exists(Shopware_Production_KernelProdContainer::class, false)) {
    \class_alias(\ContainerN3xx8ET\Shopware_Production_KernelProdContainer::class, Shopware_Production_KernelProdContainer::class, false);
}

return new \ContainerN3xx8ET\Shopware_Production_KernelProdContainer([
    'container.build_hash' => 'N3xx8ET',
    'container.build_id' => '8c6d5b4c',
    'container.build_time' => 1655820610,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN3xx8ET');
