<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZxy3rHD\Shopware_Core_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZxy3rHD/Shopware_Core_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerZxy3rHD.legacy');

    return;
}

if (!\class_exists(Shopware_Core_KernelProdContainer::class, false)) {
    \class_alias(\ContainerZxy3rHD\Shopware_Core_KernelProdContainer::class, Shopware_Core_KernelProdContainer::class, false);
}

return new \ContainerZxy3rHD\Shopware_Core_KernelProdContainer([
    'container.build_hash' => 'Zxy3rHD',
    'container.build_id' => 'c04e0bb5',
    'container.build_time' => 1655819730,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZxy3rHD');
