<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLVZEWAW\Shopware_Core_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLVZEWAW/Shopware_Core_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerLVZEWAW.legacy');

    return;
}

if (!\class_exists(Shopware_Core_KernelProdContainer::class, false)) {
    \class_alias(\ContainerLVZEWAW\Shopware_Core_KernelProdContainer::class, Shopware_Core_KernelProdContainer::class, false);
}

return new \ContainerLVZEWAW\Shopware_Core_KernelProdContainer([
    'container.build_hash' => 'LVZEWAW',
    'container.build_id' => 'ec58a39b',
    'container.build_time' => 1655819421,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLVZEWAW');
