<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGaTrTAg\Shopware_Production_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGaTrTAg/Shopware_Production_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerGaTrTAg.legacy');

    return;
}

if (!\class_exists(Shopware_Production_KernelProdContainer::class, false)) {
    \class_alias(\ContainerGaTrTAg\Shopware_Production_KernelProdContainer::class, Shopware_Production_KernelProdContainer::class, false);
}

return new \ContainerGaTrTAg\Shopware_Production_KernelProdContainer([
    'container.build_hash' => 'GaTrTAg',
    'container.build_id' => 'fc02d6d0',
    'container.build_time' => 1655826701,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGaTrTAg');
