<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLkNhJWc\Shopware_Production_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLkNhJWc/Shopware_Production_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerLkNhJWc.legacy');

    return;
}

if (!\class_exists(Shopware_Production_KernelProdContainer::class, false)) {
    \class_alias(\ContainerLkNhJWc\Shopware_Production_KernelProdContainer::class, Shopware_Production_KernelProdContainer::class, false);
}

return new \ContainerLkNhJWc\Shopware_Production_KernelProdContainer([
    'container.build_hash' => 'LkNhJWc',
    'container.build_id' => '97fe2579',
    'container.build_time' => 1655819790,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLkNhJWc');
